---
title: "Basic Eample of the pier Package"
author: "Matt Johnson"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    fig_caption: yes
    self_contained: yes
    toc: no
  pdf_document:
    toc: no
vignette: >
  %\VignetteIndexEntry{Basic usage of the pier package}
  %\VignetteEngine{knitr::rmarkdown} 
  %\VignetteEncoding{UTF-8}
---



## Data Setup


```{r data}

library(pier)
library(lubridate)

fd <- now()-months(12)

data <- data.frame(label = c('Dust','Emergency','Noise','Odour','Waste','Water','Community'),
                   value = c(104,19,638,1250,187,140,10),
                   color = c("#A6CEE3","#1F78B4","#B2DF8A",
                             "#33A02C","#FB9A99","#E31A1C",
                             "#FDBF6F"))

```


## Usage with Standard Defaults
```{r simple}

pier(data)

```

## Small Groupings

Currently this feature works as expected but the labels are lost. 

```{r small}

pier(data, smallSegmentGrouping = TRUE)

```


## Advanced Usage

```{r advanced}

pier(data) %>%
    pie.size(inner=70, outer=100, width=500, height=500) %>%
    pie.title(text='Pollution Reports', font='Impact', location='pie-center') %>%
    pie.subtitle(text='by Segement Type') %>%
    pie.footer(text=sprintf('Pollution Reports Since %s', format(fd, '%a %B %d, %Y')),
               location = 'bottom-left') %>%
    pie.tooltips()

```


